include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(PROJECT_ROOT)/make/leaf.cfg

CFLAGS+=-Werror -DNO_POPEN=1 -DNO_SSL=1 -DNO_SSI=1 -DUSE_POSIX_FEATURES=1

BASENAME=mongoose

OTHER_CLEAN_FILES=$(BASENAME).num $(BASENAME).ralf

LIB=lib$(BASENAME).a
PGM=$(BASENAME).exe
LIBOBJS=$(BASENAME).o
OBJS=$(LIBOBJS) main.o

all: $(LIB) $(PGM)

$(LIB) : $(LIBOBJS)
	@$(AR) r $(LIB) $(LIBOBJS)

$(PGM) : $(OBJS)
	@$(make-exe)

clean:
	@rm -f $(OBJS) $(LIB) $(PGM) $(OTHER_CLEAN_FILES)
