#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote .                                                             06022000                                 git@github.com:06022000/civetweb.git                                             $# $@
register_remote .                                                             Altronix                                 git@github.com:Altronix/mongoose.git                                             $# $@
register_remote .                                                             Ashibananon                              git@github.com:Ashibananon/civetweb.git                                          $# $@
register_remote .                                                             BaroboRobotics                           git@github.com:BaroboRobotics/civetweb.git                                       $# $@
register_remote .                                                             Blizzard                                 git@github.com:Blizzard/civetweb.git                                             $# $@
register_remote .                                                             CMakeezer                                git@github.com:CMakeezer/mongoose.git                                            $# $@
register_remote .                                                             CfirTsabari                              git@github.com:CfirTsabari/mongoose.git                                          $# $@
register_remote .                                                             ConstantineGochev                        git@github.com:ConstantineGochev/mongoose.git                                    $# $@
register_remote .                                                             DL6ER                                    git@github.com:DL6ER/civetweb.git                                                $# $@
register_remote .                                                             DavidKorczynski                          git@github.com:DavidKorczynski/mongoose.git                                      $# $@
register_remote .                                                             DavidNovoa                               git@github.com:DavidNovoa/mongoose.git                                           $# $@
register_remote .                                                             DrumTechnologiesLtd                      git@github.com:DrumTechnologiesLtd/civetweb.git                                  $# $@
register_remote .                                                             Genomenon                                git@github.com:Genomenon/civetweb.git                                            $# $@
register_remote .                                                             GerHobbelt                               git@github.com:GerHobbelt/mongoose-vanilla.git                                   $# $@
register_remote .                                                             GerHobbelt-original                      git@github.com:GerHobbelt/civet-webserver.git                                    $# $@
register_remote .                                                             HarDToBelieve                            git@github.com:HarDToBelieve/mongoose.git                                        $# $@
register_remote .                                                             JayyCee                                  git@github.com:JayyCee/mongoose-snprintf-warning-free.git                        $# $@
register_remote .                                                             KalifiaBillal                            git@github.com:KalifiaBillal/mongoose.git                                        $# $@
register_remote .                                                             LZhizhou                                 git@github.com:LZhizhou/civetweb.git                                             $# $@
register_remote .                                                             Lasander                                 git@github.com:Lasander/civetweb.git                                             $# $@
register_remote .                                                             LastShekel                               git@github.com:LastShekel/mongoose.git                                           $# $@
register_remote .                                                             M4GNV5                                   git@github.com:M4GNV5/mongoose.git                                               $# $@
register_remote .                                                             MGralka                                  git@github.com:MGralka/civetweb.git                                              $# $@
register_remote .                                                             MarkJonas                                git@github.com:MarkJonas/mongoose.git                                            $# $@
register_remote .                                                             MoonCollider                             git@github.com:MoonCollider/mongoose.git                                         $# $@
register_remote .                                                             Nukersson                                git@github.com:Nukersson/civetweb.git                                            $# $@
register_remote .                                                             Othernet-Project                         git@github.com:Othernet-Project/civetweb.git                                     $# $@
register_remote .                                                             Papafox                                  git@github.com:Papafox/mongoose.git                                              $# $@
register_remote .                                                             Proemion                                 git@github.com:Proemion/mongoose-cpp.git                                         $# $@
register_remote .                                                             QXSoftware                               git@github.com:QXSoftware/civetweb.git                                           $# $@
register_remote .                                                             Qinch                                    git@github.com:Qinch/civetweb.git                                                $# $@
register_remote .                                                             QuinnDamerell                            git@github.com:QuinnDamerell/mongoose.git                                        $# $@
register_remote .                                                             RajaTaimur7                              git@github.com:RajaTaimur7/civetweb.git                                          $# $@
register_remote .                                                             RektInator                               git@github.com:RektInator/mongoose-cpp.git                                       $# $@
register_remote .                                                             WartyWarthog                             git@github.com:WartyWarthog/civetweb.git                                         $# $@
register_remote .                                                             YankunLi                                 git@github.com:YankunLi/mongoose.git                                             $# $@
register_remote .                                                             ac                                       git@github.com:ac/civetweb.git                                                   $# $@
register_remote .                                                             acridacute                               git@github.com:acridacute/civetweb.git                                           $# $@
register_remote .                                                             actonDev                                 git@github.com:actonDev/mongoose.git                                             $# $@
register_remote .                                                             akrpic77                                 git@github.com:akrpic77/mongoose.git                                             $# $@
register_remote .                                                             alexhod                                  git@github.com:alexhod/mongoose.git                                              $# $@
register_remote .                                                             antmicro                                 git@github.com:antmicro/civetweb.git                                             $# $@
register_remote .                                                             argylelabcoat                            git@github.com:argylelabcoat/civetweb.git                                        $# $@
register_remote .                                                             awong-dev                                git@github.com:awong-dev/mongoose.git                                            $# $@
register_remote .                                                             azadkuh                                  git@github.com:azadkuh/mongoose.git                                              $# $@
register_remote .                                                             bacox                                    git@github.com:bacox/mongoose-cpp.git                                            $# $@
register_remote .                                                             beyondkyq                                git@github.com:beyondkyq/mongoose.git                                            $# $@
register_remote .                                                             buckaroo-pm                              git@github.com:buckaroo-pm/cesanta-mongoose.git                                  $# $@
register_remote .                                                             cabbagecabin                             git@github.com:cabbagecabin/civetweb.git                                         $# $@
register_remote .                                                             ceph                                     git@github.com:ceph/civetweb.git                                                 $# $@
register_remote .                                                             cesanta                                  git@github.com:cesanta/mongoose.git                                              $# $@
register_remote .                                                             chainware                                git@github.com:chainware/mongoose.git                                            $# $@
register_remote .                                                             civetweb                                 git@github.com:civetweb/civetweb.git                                             $# $@
register_remote .                                                             cmadh                                    git@github.com:cmadh/civetweb.git                                                $# $@
register_remote .                                                             comphack                                 git@github.com:comphack/civetweb.git                                             $# $@
register_remote .                                                             coolsnake                                git@github.com:coolsnake/mongoose.git                                            $# $@
register_remote .                                                             couchbasedeps                            git@github.com:couchbasedeps/civetweb.git                                        $# $@
register_remote .                                                             cpp-pm                                   git@github.com:cpp-pm/civetweb.git                                               $# $@
register_remote .                                                             cpp-sc2                                  git@github.com:cpp-sc2/civetweb.git                                              $# $@
register_remote .                                                             csy1983                                  git@github.com:csy1983/mongoose.git                                              $# $@
register_remote .                                                             d4rkmen                                  git@github.com:d4rkmen/mongoose.git                                              $# $@
register_remote .                                                             dbmarch                                  git@github.com:dbmarch/mongoose.git                                              $# $@
register_remote .                                                             dg-dboehi                                git@github.com:dg-dboehi/mongoose.git                                            $# $@
register_remote .                                                             dmundt                                   git@github.com:dmundt/mongoose.git                                               $# $@
register_remote .                                                             dooglz                                   git@github.com:dooglz/mongoose.git                                               $# $@
register_remote .                                                             elisemorysc                              git@github.com:elisemorysc/civetweb.git                                          $# $@
register_remote .                                                             fuzzitdev                                git@github.com:fuzzitdev/mongoose.git                                            $# $@
register_remote .                                                             general252                               git@github.com:general252/mongoose.git                                           $# $@
register_remote .                                                             graft-project                            git@github.com:graft-project/mongoose.git                                        $# $@
register_remote .                                                             gungfu2012                               git@github.com:gungfu2012/mongoose.git                                           $# $@
register_remote .                                                             guywilson                                git@github.com:guywilson/mongoose.git                                            $# $@
register_remote .                                                             hakabahitoyo                             git@github.com:hakabahitoyo/mongoose.git                                         $# $@
register_remote .                                                             hansipie                                 git@github.com:hansipie/civetweb.git                                             $# $@
register_remote .                                                             hefloryd                                 git@github.com:hefloryd/civetweb.git                                             $# $@
register_remote .                                                             herbrechtsmeier                          git@github.com:herbrechtsmeier/mongoose.git                                      $# $@
register_remote .                                                             hojalot                                  git@github.com:hojalot/civetweb.git                                              $# $@
register_remote .                                                             houmingyuan                              git@github.com:houmingyuan/mongoose.git                                          $# $@
register_remote .                                                             hunter-packages                          git@github.com:hunter-packages/civetweb.git                                      $# $@
register_remote .                                                             idigger                                  git@github.com:idigger/mongoose.git                                              $# $@
register_remote .                                                             impradeepgupta                           git@github.com:impradeepgupta/civetweb.git                                       $# $@
register_remote .                                                             ishikawash                               git@github.com:ishikawash/mongoose.git                                           $# $@
register_remote .                                                             jagoyette                                git@github.com:jagoyette/mongoose.git                                            $# $@
register_remote .                                                             jcorporation                             git@github.com:jcorporation/mongoose.git                                         $# $@
register_remote .                                                             jdetaeye                                 git@github.com:jdetaeye/civetweb.git                                             $# $@
register_remote .                                                             jelledevleeschouwer                      git@github.com:jelledevleeschouwer/mongoose.git                                  $# $@
register_remote .                                                             jeremypoulter                            git@github.com:jeremypoulter/mongoose.git                                        $# $@
register_remote .                                                             jiangzhuti                               git@github.com:jiangzhuti/mongoose.git                                           $# $@
register_remote .                                                             jknowles888                              git@github.com:jknowles888/civetweb.git                                          $# $@
register_remote .                                                             jneuhauser                               git@github.com:jneuhauser/mongoose.git                                           $# $@
register_remote .                                                             jodogne                                  git@github.com:jodogne/civetweb.git                                              $# $@
register_remote .                                                             jyane                                    git@github.com:jyane/mongoose-cpp.git                                            $# $@
register_remote .                                                             kaelco                                   git@github.com:kaelco/mongoose.git                                               $# $@
register_remote .                                                             kamit9171                                git@github.com:kamit9171/civetweb.git                                            $# $@
register_remote .                                                             khanhbui                                 git@github.com:khanhbui/civetweb.git                                             $# $@
register_remote .                                                             kokizzu                                  git@github.com:kokizzu/mongoose.git                                              $# $@
register_remote .                                                             kongque                                  git@github.com:kongque/mongoose.git                                              $# $@
register_remote .                                                             krzk                                     git@github.com:krzk/civetweb.git                                                 $# $@
register_remote .                                                             kzanev                                   git@github.com:kzanev/mongoose.git                                               $# $@
register_remote .                                                             libeio                                   git@github.com:libeio/mongoose.git                                               $# $@
register_remote .                                                             liusubin                                 git@github.com:liusubin/mongoose-cpp.git                                         $# $@
register_remote .                                                             lnksz                                    git@github.com:lnksz/mongoose.git                                                $# $@
register_remote .                                                             lt-holman                                git@github.com:lt-holman/civetweb.git                                            $# $@
register_remote .                                                             mdw-at-linuxbox                          git@github.com:mdw-at-linuxbox/civetweb-1.git                                    $# $@
register_remote .                                                             mimikgit                                 git@github.com:mimikgit/civetweb.git                                             $# $@
register_remote .                                                             mirandacong                              git@github.com:mirandacong/civetweb.git                                          $# $@
register_remote .                                                             mrexodia                                 git@github.com:mrexodia/civetweb.git                                             $# $@
register_remote .                                                             mulle-nat                                git@github.com:mulle-nat/civetweb.git                                            $# $@
register_remote .                                                             n0va-scy                                 git@github.com:n0va-scy/mongoose.git                                             $# $@
register_remote .                                                             n0whereman                               git@github.com:n0whereman/civet-webserver.git                                    $# $@
register_remote .                                                             nejordan15                               git@github.com:nejordan15/mongoose.git                                           $# $@
register_remote .                                                             netCommonsEU                             git@github.com:netCommonsEU/mongoose.git                                         $# $@
register_remote .                                                             niicoooo                                 git@github.com:niicoooo/mongoose.git                                             $# $@
register_remote .                                                             norzak                                   git@github.com:norzak/civetweb.git                                               $# $@
register_remote .                                                             openvehicles                             git@github.com:openvehicles/mongoose.git                                         $# $@
register_remote .                                                             oplinkoms                                git@github.com:oplinkoms/mongoose.git                                            $# $@
register_remote .                                                             part1zano                                git@github.com:part1zano/mongoose-cpp.git                                        $# $@
register_remote .                                                             pbeyeler                                 git@github.com:pbeyeler/mongoose.git                                             $# $@
register_remote .                                                             plan44                                   git@github.com:plan44/civetweb.git                                               $# $@
register_remote .                                                             pponnuvel                                git@github.com:pponnuvel/civetweb.git                                            $# $@
register_remote .                                                             richard1999                              git@github.com:richard1999/civetweb.git                                          $# $@
register_remote .                                                             rishavbhowmik                            git@github.com:rishavbhowmik/mongoose.git                                        $# $@
register_remote .                                                             rkbk2000                                 git@github.com:rkbk2000/mongoose.git                                             $# $@
register_remote .                                                             robothobin                               git@github.com:robothobin/mongoose.git                                           $# $@
register_remote .                                                             rockeet                                  git@github.com:rockeet/civetweb.git                                              $# $@
register_remote .                                                             rxwen                                    git@github.com:rxwen/mongoose.git                                                $# $@
register_remote .                                                             ryanbinns                                git@github.com:ryanbinns/civetweb.git                                            $# $@
register_remote .                                                             s4mux                                    git@github.com:s4mux/mongoose.git                                                $# $@
register_remote .                                                             saidinesh5                               git@github.com:saidinesh5/mongoose.git                                           $# $@
register_remote .                                                             sajanshakya129                           git@github.com:sajanshakya129/mongoose.git                                       $# $@
register_remote .                                                             sameor                                   git@github.com:sameor/civetweb.git                                               $# $@
register_remote .                                                             sebgod                                   git@github.com:sebgod/mongoose.git                                               $# $@
register_remote .                                                             shablov                                  git@github.com:shablov/civetweb.git                                              $# $@
register_remote .                                                             shreyajaggi8                             git@github.com:shreyajaggi8/civetweb.git                                         $# $@
register_remote .                                                             soooooong                                git@github.com:soooooong/mongoose.git                                            $# $@
register_remote .                                                             stefb965                                 git@github.com:stefb965/mongoose.git                                             $# $@
register_remote .                                                             swq123459                                git@github.com:swq123459/mongoose.git                                            $# $@
register_remote .                                                             takryo00                                 git@github.com:takryo00/mongoose-cpp.git                                         $# $@
register_remote .                                                             teddywest32                              git@github.com:teddywest32/civetweb.git                                          $# $@
register_remote .                                                             theanalyst                               git@github.com:theanalyst/civetweb.git                                           $# $@
register_remote .                                                             tsieprawski                              git@github.com:tsieprawski/mongoose.git                                          $# $@
register_remote .                                                             turbulenz                                git@github.com:turbulenz/civetweb.git                                            $# $@
register_remote .                                                             tweenk                                   git@github.com:tweenk/civetweb.git                                               $# $@
register_remote .                                                             uilianries                               git@github.com:uilianries/civetweb.git                                           $# $@
register_remote .                                                             uk0                                      git@github.com:uk0/mongoose.git                                                  $# $@
register_remote .                                                             ullenius                                 git@github.com:ullenius/mongoose.git                                             $# $@
register_remote .                                                             vvhh2002                                 git@github.com:vvhh2002/mongoose.git                                             $# $@
register_remote .                                                             wang-xin-xin                             git@github.com:wang-xin-xin/mongoose.git                                         $# $@
register_remote .                                                             weiswift                                 git@github.com:weiswift/civetweb.git                                             $# $@
register_remote .                                                             xfbs                                     git@github.com:xfbs/mongoose.git                                                 $# $@
register_remote .                                                             xhpohanka                                git@github.com:xhpohanka/civetweb.git                                            $# $@
register_remote .                                                             xin-f                                    git@github.com:xin-f/mongoose.git                                                $# $@
register_remote .                                                             xtne6f                                   git@github.com:xtne6f/civetweb.git                                               $# $@
register_remote .                                                             yzngo                                    git@github.com:yzngo/civetweb.git                                                $# $@
register_remote .                                                             zamnedix                                 git@github.com:zamnedix/mongoose.git                                             $# $@
register_remote .                                                             zephyrproject-rtos                       git@github.com:zephyrproject-rtos/civetweb.git                                   $# $@
register_remote .                                                             zeus-smart-home                          git@github.com:zeus-smart-home/mongoose.git                                      $# $@
register_remote .                                                             zhumxcq                                  git@github.com:zhumxcq/civetweb.git                                              $# $@
register_remote .                                                             zuckschwerdt                             git@github.com:zuckschwerdt/mongoose.git                                         $# $@
register_remote .                                                             zuzy                                     git@github.com:zuzy/mongoose.git                                                 $# $@
register_remote pthread-win32                                                 BlazesRus                                git@github.com:BlazesRus/pthread-win32.git                                       $# $@
register_remote pthread-win32                                                 Cinegy                                   git@github.com:Cinegy/pthread-win32.git                                          $# $@
register_remote pthread-win32                                                 DeckerSU                                 git@github.com:DeckerSU/pthread-win32.git                                        $# $@
register_remote pthread-win32                                                 GerHobbelt                               git@github.com:GerHobbelt/pthread-win32.git                                      $# $@
register_remote pthread-win32                                                 Puasonych                                git@github.com:Puasonych/pthread-win32.git                                       $# $@
register_remote pthread-win32                                                 UltraCombos                              git@github.com:UltraCombos/pthread-win32.git                                     $# $@
register_remote pthread-win32                                                 gandalfliang                             git@github.com:gandalfliang/pthread-win32.git                                    $# $@
register_remote pthread-win32                                                 h2obrain                                 git@github.com:h2obrain/pthread-win32.git                                        $# $@
register_remote pthread-win32                                                 hayguen                                  git@github.com:hayguen/pthread-win32.git                                         $# $@
register_remote pthread-win32                                                 oktonion                                 git@github.com:oktonion/pthread-win32.git                                        $# $@
register_remote pthread-win32                                                 pierreguillot                            git@github.com:pierreguillot/pthread-win32.git                                   $# $@
register_remote pthread-win32                                                 rs0h                                     git@github.com:rs0h/pthread-win32.git                                            $# $@
register_remote upskirt                                                       7890                                     git@github.com:7890/sundown.git                                                  $# $@
register_remote upskirt                                                       CBDB1LOVE                                git@github.com:CBDB1LOVE/sundown.git                                             $# $@
register_remote upskirt                                                       DGHeroin                                 git@github.com:DGHeroin/sundown.git                                              $# $@
register_remote upskirt                                                       Daij-Djan                                git@github.com:Daij-Djan/sundown.git                                             $# $@
register_remote upskirt                                                       GerHobbelt                               git@github.com:GerHobbelt/upskirt.git                                            $# $@
register_remote upskirt                                                       LibrePCB                                 git@github.com:LibrePCB/hoedown.git                                              $# $@
register_remote upskirt                                                       PeterXu                                  git@github.com:PeterXu/hoedown.git                                               $# $@
register_remote upskirt                                                       RockfordWei                              git@github.com:RockfordWei/upskirt.git                                           $# $@
register_remote upskirt                                                       SanderMertens                            git@github.com:SanderMertens/hoedown.git                                         $# $@
register_remote upskirt                                                       UbunHub                                  git@github.com:UbunHub/hoedown.git                                               $# $@
register_remote upskirt                                                       ahssas                                   git@github.com:ahssas/sundown.git                                                $# $@
register_remote upskirt                                                       akinozgen                                git@github.com:akinozgen/scidown.git                                             $# $@
register_remote upskirt                                                       almassapargali                           git@github.com:almassapargali/sundown.git                                        $# $@
register_remote upskirt                                                       analog-cbarber                           git@github.com:analog-cbarber/hoedown.git                                        $# $@
register_remote upskirt                                                       andygeers                                git@github.com:andygeers/sundown.git                                             $# $@
register_remote upskirt                                                       apiaryio                                 git@github.com:apiaryio/sundown.git                                              $# $@
register_remote upskirt                                                       apnadkarni                               git@github.com:apnadkarni/hoedown.git                                            $# $@
register_remote upskirt                                                       aroben                                   git@github.com:aroben/sundown.git                                                $# $@
register_remote upskirt                                                       beingryu                                 git@github.com:beingryu/sundown.git                                              $# $@
register_remote upskirt                                                       bigjason                                 git@github.com:bigjason/sundown.git                                              $# $@
register_remote upskirt                                                       bmcculley                                git@github.com:bmcculley/hoedown.git                                             $# $@
register_remote upskirt                                                       chr-1x                                   git@github.com:chr-1x/sd_markdown.git                                            $# $@
register_remote upskirt                                                       clemensg                                 git@github.com:clemensg/hoedown.git                                              $# $@
register_remote upskirt                                                       cloose                                   git@github.com:cloose/hoedown.git                                                $# $@
register_remote upskirt                                                       danffer2019                              git@github.com:danffer2019/hoedown.git                                           $# $@
register_remote upskirt                                                       datacratic                               git@github.com:datacratic/hoedown.git                                            $# $@
register_remote upskirt                                                       davidask                                 git@github.com:davidask/hoedown.git                                              $# $@
register_remote upskirt                                                       davidpshea                               git@github.com:davidpshea/sundown.git                                            $# $@
register_remote upskirt                                                       dispatchqueue                            git@github.com:dispatchqueue/sundown.git                                         $# $@
register_remote upskirt                                                       doo                                      git@github.com:doo/hoedown.git                                                   $# $@
register_remote upskirt                                                       eichlan                                  git@github.com:eichlan/sundown.git                                               $# $@
register_remote upskirt                                                       errpro                                   git@github.com:errpro/sundown.git                                                $# $@
register_remote upskirt                                                       fabb                                     git@github.com:fabb/sundown.git                                                  $# $@
register_remote upskirt                                                       fappelman                                git@github.com:fappelman/hoedown.git                                             $# $@
register_remote upskirt                                                       faywong                                  git@github.com:faywong/scidown.git                                               $# $@
register_remote upskirt                                                       fergaschas                               git@github.com:fergaschas/hoedown.git                                            $# $@
register_remote upskirt                                                       fluffy-critter                           git@github.com:fluffy-critter/hoedown.git                                        $# $@
register_remote upskirt                                                       freron                                   git@github.com:freron/upskirt.git                                                $# $@
register_remote upskirt                                                       gagern                                   git@github.com:gagern/hoedown.git                                                $# $@
register_remote upskirt                                                       gampleman                                git@github.com:gampleman/Sunrise.git                                             $# $@
register_remote upskirt                                                       geoffmcl                                 git@github.com:geoffmcl/scidown.git                                              $# $@
register_remote upskirt                                                       hispeedimagins                           git@github.com:hispeedimagins/hoedown.git                                        $# $@
register_remote upskirt                                                       ignatenkobrain                           git@github.com:ignatenkobrain/hoedown.git                                        $# $@
register_remote upskirt                                                       jacksonh                                 git@github.com:jacksonh/sundown.git                                              $# $@
register_remote upskirt                                                       jasharpe                                 git@github.com:jasharpe/hoedown.git                                              $# $@
register_remote upskirt                                                       jayvn                                    git@github.com:jayvn/hoedown.git                                                 $# $@
register_remote upskirt                                                       jgoz                                     git@github.com:jgoz/sundown.git                                                  $# $@
register_remote upskirt                                                       jimmyjxiao                               git@github.com:jimmyjxiao/hoedown-cpp.git                                        $# $@
register_remote upskirt                                                       jjude                                    git@github.com:jjude/sundown.git                                                 $# $@
register_remote upskirt                                                       jmtd                                     git@github.com:jmtd/sundown.git                                                  $# $@
register_remote upskirt                                                       jnicklas                                 git@github.com:jnicklas/sundown.git                                              $# $@
register_remote upskirt                                                       jsoref                                   git@github.com:jsoref/hoedown.git                                                $# $@
register_remote upskirt                                                       kidaak                                   git@github.com:kidaak/sundown.git                                                $# $@
register_remote upskirt                                                       krig                                     git@github.com:krig/hoedown.git                                                  $# $@
register_remote upskirt                                                       lepture                                  git@github.com:lepture/hoedown.git                                               $# $@
register_remote upskirt                                                       locallycompact                           git@github.com:locallycompact/hoedown.git                                        $# $@
register_remote upskirt                                                       marc-sturm                               git@github.com:marc-sturm/sundown.git                                            $# $@
register_remote upskirt                                                       marcheiligers                            git@github.com:marcheiligers/sundown.git                                         $# $@
register_remote upskirt                                                       meldonization                            git@github.com:meldonization/hoedown.git                                         $# $@
register_remote upskirt                                                       mikecsh                                  git@github.com:mikecsh/hoedown.git                                               $# $@
register_remote upskirt                                                       mildsunrise                              git@github.com:mildsunrise/hoedown.git                                           $# $@
register_remote upskirt                                                       milgner                                  git@github.com:milgner/sundown.git                                               $# $@
register_remote upskirt                                                       mingodad                                 git@github.com:mingodad/sundown.git                                              $# $@
register_remote upskirt                                                       njlr                                     git@github.com:njlr/sundown.git                                                  $# $@
register_remote upskirt                                                       nkhorman                                 git@github.com:nkhorman/hoedown.git                                              $# $@
register_remote upskirt                                                       nullice                                  git@github.com:nullice/sundown.git                                               $# $@
register_remote upskirt                                                       parallaxinc                              git@github.com:parallaxinc/hoedown.git                                           $# $@
register_remote upskirt                                                       pazos                                    git@github.com:pazos/hoedown.git                                                 $# $@
register_remote upskirt                                                       randomatom                               git@github.com:randomatom/hoedown-mweb.git                                       $# $@
register_remote upskirt                                                       robin                                    git@github.com:robin/sundown.git                                                 $# $@
register_remote upskirt                                                       rschiang                                 git@github.com:rschiang/hoedown.git                                              $# $@
register_remote upskirt                                                       rust-lang                                git@github.com:rust-lang/hoedown.git                                             $# $@
register_remote upskirt                                                       safx                                     git@github.com:safx/hoedown.git                                                  $# $@
register_remote upskirt                                                       sim0629                                  git@github.com:sim0629/sundown.git                                               $# $@
register_remote upskirt                                                       strivingboy                              git@github.com:strivingboy/hoedown.git                                           $# $@
register_remote upskirt                                                       tamlok                                   git@github.com:tamlok/hoedown.git                                                $# $@
register_remote upskirt                                                       txdv                                     git@github.com:txdv/sundown.git                                                  $# $@
register_remote upskirt                                                       waldyrious                               git@github.com:waldyrious/hoedown.git                                            $# $@
register_remote upskirt                                                       yoannsculo                               git@github.com:yoannsculo/sundown.git                                            $# $@
register_remote upskirt                                                       zababurinsv                              git@github.com:zababurinsv/sundown.git                                           $# $@



popd                                                                            2> /dev/null   > /dev/null

