#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  tools/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote .                                                             BaroboRobotics                           git@github.com:BaroboRobotics/civetweb.git                                       $# $@
register_remote .                                                             CognitiveNetworks                        git@github.com:CognitiveNetworks/civetweb.git                                    $# $@
register_remote .                                                             Enseed                                   git@github.com:Enseed/civetweb.git                                               $# $@
register_remote .                                                             Grahack                                  git@github.com:Grahack/civetweb.git                                              $# $@
register_remote .                                                             NetDevLtd                                git@github.com:NetDevLtd/civetweb.git                                            $# $@
register_remote .                                                             Rjinswand                                git@github.com:Rjinswand/civetweb.git                                            $# $@
register_remote .                                                             SafwatHalaby                             git@github.com:SafwatHalaby/civetweb.git                                         $# $@
register_remote .                                                             alemv                                    git@github.com:alemv/civetweb.git                                                $# $@
register_remote .                                                             apetrone                                 git@github.com:apetrone/civetweb.git                                             $# $@
register_remote .                                                             c2go                                     git@github.com:c2go/civetweb.git                                                 $# $@
register_remote .                                                             cdbishop                                 git@github.com:cdbishop/civetweb.git                                             $# $@
register_remote .                                                             ceph                                     git@github.com:ceph/civetweb.git                                                 $# $@
register_remote .                                                             civetweb                                 git@github.com:civetweb/civetweb.git                                             $# $@
register_remote .                                                             dalgaaf                                  git@github.com:dalgaaf/civetweb.git                                              $# $@
register_remote .                                                             detro                                    git@github.com:detro/civetweb.git                                                $# $@
register_remote .                                                             fgaranda                                 git@github.com:fgaranda/civetweb.git                                             $# $@
register_remote .                                                             jdblair                                  git@github.com:jdblair/civetweb.git                                              $# $@
register_remote .                                                             jesperes                                 git@github.com:jesperes/civetweb.git                                             $# $@
register_remote .                                                             leonardosantos                           git@github.com:leonardosantos/civetta.git                                        $# $@
register_remote .                                                             rpetrich                                 git@github.com:rpetrich/civetweb.git                                             $# $@
register_remote .                                                             rzarzynski                               git@github.com:rzarzynski/civetweb.git                                           $# $@
register_remote .                                                             samcrow                                  git@github.com:samcrow/civetweb.git                                              $# $@
register_remote .                                                             shawnye                                  git@github.com:shawnye/civetweb.git                                              $# $@
register_remote .                                                             tnoho                                    git@github.com:tnoho/civetweb.git                                                $# $@
register_remote .                                                             tracedev                                 git@github.com:tracedev/civetweb.git                                             $# $@
register_remote .                                                             uhertlein                                git@github.com:uhertlein/civetweb.git                                            $# $@
register_remote .                                                             vcatechnology                            git@github.com:vcatechnology/civetweb.git                                        $# $@
register_remote .                                                             xtne6f                                   git@github.com:xtne6f/civetweb.git                                               $# $@
register_remote src/thirdparty/duktape                                        418sec                                   git@github.com:418sec/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        ADFTech                                  git@github.com:ADFTech/duktape_fork_adf.git                                      $# $@
register_remote src/thirdparty/duktape                                        Asjidkalam                               git@github.com:Asjidkalam/duktape.git                                            $# $@
register_remote src/thirdparty/duktape                                        CG-SS                                    git@github.com:CG-SS/duktape-esp32.git                                           $# $@
register_remote src/thirdparty/duktape                                        Constellation                            git@github.com:Constellation/duktape.git                                         $# $@
register_remote src/thirdparty/duktape                                        EDI-Systems                              git@github.com:EDI-Systems/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        Ebiroll                                  git@github.com:Ebiroll/duktape-esp32.git                                         $# $@
register_remote src/thirdparty/duktape                                        EdwardBetts                              git@github.com:EdwardBetts/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        GerHobbelt                               git@github.com:GerHobbelt/duktape.git                                            $# $@
register_remote src/thirdparty/duktape                                        Hello71                                  git@github.com:Hello71/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        JARVIS-AI                                git@github.com:JARVIS-AI/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        JacksonTian                              git@github.com:JacksonTian/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        LJason77                                 git@github.com:LJason77/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        LaszloLango                              git@github.com:LaszloLango/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        LynxChaus                                git@github.com:LynxChaus/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        MakerAsia                                git@github.com:MakerAsia/duktape-esp32.git                                       $# $@
register_remote src/thirdparty/duktape                                        MilkTool                                 git@github.com:MilkTool/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        NancyLi1013                              git@github.com:NancyLi1013/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        ReneHollander                            git@github.com:ReneHollander/duktape.git                                         $# $@
register_remote src/thirdparty/duktape                                        RomeroMalaquias                          git@github.com:RomeroMalaquias/duktape.git                                       $# $@
register_remote src/thirdparty/duktape                                        Salleodore                               git@github.com:Salleodore/duktape.git                                            $# $@
register_remote src/thirdparty/duktape                                        SamHellawell                             git@github.com:SamHellawell/duktape.git                                          $# $@
register_remote src/thirdparty/duktape                                        Squareys                                 git@github.com:Squareys/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        TheBrokenRail                            git@github.com:TheBrokenRail/duktape.git                                         $# $@
register_remote src/thirdparty/duktape                                        WilliamParks                             git@github.com:WilliamParks/duktape.git                                          $# $@
register_remote src/thirdparty/duktape                                        akosthekiss                              git@github.com:akosthekiss/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        andoma                                   git@github.com:andoma/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        anju2408                                 git@github.com:anju2408/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        apjanke                                  git@github.com:apjanke/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        arguiot                                  git@github.com:arguiot/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        beevik                                   git@github.com:beevik/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        benjymous                                git@github.com:benjymous/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        boneskull                                git@github.com:boneskull/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        braindigitalis                           git@github.com:braindigitalis/duktape.git                                        $# $@
register_remote src/thirdparty/duktape                                        chris-y                                  git@github.com:chris-y/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        coolniu                                  git@github.com:coolniu/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        crazyjul                                 git@github.com:crazyjul/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        dc6jgk                                   git@github.com:dc6jgk/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        dreamflyforever                          git@github.com:dreamflyforever/duktape.git                                       $# $@
register_remote src/thirdparty/duktape                                        eddieh                                   git@github.com:eddieh/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        ffontaine                                git@github.com:ffontaine/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        frida                                    git@github.com:frida/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        gertom                                   git@github.com:gertom/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        gonzus                                   git@github.com:gonzus/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        haosu1987                                git@github.com:haosu1987/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        harold-b                                 git@github.com:harold-b/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        hasevr                                   git@github.com:hasevr/duktape-esp32.git                                          $# $@
register_remote src/thirdparty/duktape                                        hf                                       git@github.com:hf/duktape.git                                                    $# $@
register_remote src/thirdparty/duktape                                        huadream                                 git@github.com:huadream/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        jaseg                                    git@github.com:jaseg/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        jasonkajita                              git@github.com:jasonkajita/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        jchlapinski                              git@github.com:jchlapinski/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        jmhmccr                                  git@github.com:jmhmccr/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        jmptrader                                git@github.com:jmptrader/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        kahunamoore                              git@github.com:kahunamoore/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        kaisatec                                 git@github.com:kaisatec/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        kphillisjr                               git@github.com:kphillisjr/duktape.git                                            $# $@
register_remote src/thirdparty/duktape                                        legimet                                  git@github.com:legimet/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        leres                                    git@github.com:leres/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        logiconcepts819                          git@github.com:logiconcepts819/duktape.git                                       $# $@
register_remote src/thirdparty/duktape                                        luisbg                                   git@github.com:luisbg/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        lukasa1993                               git@github.com:lukasa1993/duktape-esp32.git                                      $# $@
register_remote src/thirdparty/duktape                                        lzubiaur                                 git@github.com:lzubiaur/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        magul                                    git@github.com:magul/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        mamod                                    git@github.com:mamod/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        martinetd                                git@github.com:martinetd/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        michalkas                                git@github.com:michalkas/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        mike-lischke                             git@github.com:mike-lischke/duktape.git                                          $# $@
register_remote src/thirdparty/duktape                                        mimikgit                                 git@github.com:mimikgit/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        mozeal                                   git@github.com:mozeal/duktape-esp32.git                                          $# $@
register_remote src/thirdparty/duktape                                        ndob                                     git@github.com:ndob/duktape.git                                                  $# $@
register_remote src/thirdparty/duktape                                        nickmain                                 git@github.com:nickmain/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        nkolban                                  git@github.com:nkolban/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        nkolban-esp32                            git@github.com:nkolban/duktape-esp32.git                                         $# $@
register_remote src/thirdparty/duktape                                        ocrow                                    git@github.com:ocrow/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        panliang                                 git@github.com:panliang/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        podsvirov                                git@github.com:podsvirov/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        redien                                   git@github.com:redien/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        remko                                    git@github.com:remko/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        remoe                                    git@github.com:remoe/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        rksht                                    git@github.com:rksht/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        ryfow                                    git@github.com:ryfow/duktape-esp32.git                                           $# $@
register_remote src/thirdparty/duktape                                        saghul                                   git@github.com:saghul/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        skeptycal                                git@github.com:skeptycal/duktape.git                                             $# $@
register_remote src/thirdparty/duktape                                        skomski                                  git@github.com:skomski/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        squarealfa                               git@github.com:squarealfa/duktape.git                                            $# $@
register_remote src/thirdparty/duktape                                        sstruchtrup                              git@github.com:sstruchtrup/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        stevefan1999-personal                    git@github.com:stevefan1999-personal/duktape.git                                 $# $@
register_remote src/thirdparty/duktape                                        svaarala                                 git@github.com:svaarala/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        svaarala-original                        git@github.com:svaarala/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        technosaurus                             git@github.com:technosaurus/duktape.git                                          $# $@
register_remote src/thirdparty/duktape                                        u0yiji1                                  git@github.com:u0yiji1/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        unamer                                   git@github.com:unamer/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        webfolderio                              git@github.com:webfolderio/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        weilianglin                              git@github.com:weilianglin/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        wenq1                                    git@github.com:wenq1/duktape.git                                                 $# $@
register_remote src/thirdparty/duktape                                        whorfin                                  git@github.com:whorfin/duktape.git                                               $# $@
register_remote src/thirdparty/duktape                                        yrashk                                   git@github.com:yrashk/duktape.git                                                $# $@
register_remote src/thirdparty/duktape                                        zhaijialong                              git@github.com:zhaijialong/duktape.git                                           $# $@
register_remote src/thirdparty/duktape                                        zimbabao                                 git@github.com:zimbabao/duktape.git                                              $# $@
register_remote src/thirdparty/duktape                                        zlguo1996                                git@github.com:zlguo1996/duktape-esp32.git                                       $# $@
register_remote src/thirdparty/lua                                            GerHobbelt                               git@github.com:GerHobbelt/lua.git                                                $# $@
register_remote src/thirdparty/lua                                            lua-original                             git@github.com:lua/lua.git                                                       $# $@
register_remote src/thirdparty/luafilesystem                                  AdUki                                    git@github.com:AdUki/luafilesystem.git                                           $# $@
register_remote src/thirdparty/luafilesystem                                  Adriatic1                                git@github.com:Adriatic1/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  BangWork                                 git@github.com:BangWork/luafilesystem.git                                        $# $@
register_remote src/thirdparty/luafilesystem                                  EpicNetwork                              git@github.com:EpicNetwork/luafilesystem.git                                     $# $@
register_remote src/thirdparty/luafilesystem                                  Eroica                                   git@github.com:Eroica/luafilesystem.git                                          $# $@
register_remote src/thirdparty/luafilesystem                                  FutureProcessing                         git@github.com:FutureProcessing/luafilesystem.git                                $# $@
register_remote src/thirdparty/luafilesystem                                  GerHobbelt                               git@github.com:GerHobbelt/luafilesystem.git                                      $# $@
register_remote src/thirdparty/luafilesystem                                  JinseSunShine                            git@github.com:JinseSunShine/LuaDist-luafilesystem.git                           $# $@
register_remote src/thirdparty/luafilesystem                                  MichoChan                                git@github.com:MichoChan/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  RPG3D                                    git@github.com:RPG3D/luafilesystem.git                                           $# $@
register_remote src/thirdparty/luafilesystem                                  Rasa0                                    git@github.com:Rasa0/luafilesystem.git                                           $# $@
register_remote src/thirdparty/luafilesystem                                  StoneDot                                 git@github.com:StoneDot/luafilesystem.git                                        $# $@
register_remote src/thirdparty/luafilesystem                                  TheCycoONE                               git@github.com:TheCycoONE/luafilesystem.git                                      $# $@
register_remote src/thirdparty/luafilesystem                                  andrewstarks                             git@github.com:andrewstarks/luafilesystem.git                                    $# $@
register_remote src/thirdparty/luafilesystem                                  appwilldev                               git@github.com:appwilldev/luafilesystem.git                                      $# $@
register_remote src/thirdparty/luafilesystem                                  blockchainhelp                           git@github.com:blockchainhelp/luafilesystem.git                                  $# $@
register_remote src/thirdparty/luafilesystem                                  chrisBirmingham                          git@github.com:chrisBirmingham/luafilesystem.git                                 $# $@
register_remote src/thirdparty/luafilesystem                                  cn00                                     git@github.com:cn00/luafilesystem.git                                            $# $@
register_remote src/thirdparty/luafilesystem                                  cryon-io                                 git@github.com:cryon-io/luafilesystem.git                                        $# $@
register_remote src/thirdparty/luafilesystem                                  czlc                                     git@github.com:czlc/luafilesystem.git                                            $# $@
register_remote src/thirdparty/luafilesystem                                  dibyendumajumdar                         git@github.com:dibyendumajumdar/ravi-filesystem.git                              $# $@
register_remote src/thirdparty/luafilesystem                                  doub                                     git@github.com:doub/luafilesystem.git                                            $# $@
register_remote src/thirdparty/luafilesystem                                  edubart                                  git@github.com:edubart/luafilesystem.git                                         $# $@
register_remote src/thirdparty/luafilesystem                                  elikosan                                 git@github.com:elikosan/luafilesystem.git                                        $# $@
register_remote src/thirdparty/luafilesystem                                  ewmailing                                git@github.com:ewmailing/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  fengye                                   git@github.com:fengye/luafilesystem.git                                          $# $@
register_remote src/thirdparty/luafilesystem                                  gdyr                                     git@github.com:gdyr/LuaFileBox.git                                               $# $@
register_remote src/thirdparty/luafilesystem                                  gvvaughan                                git@github.com:gvvaughan/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  happiykj                                 git@github.com:happiykj/luafilesystem.git                                        $# $@
register_remote src/thirdparty/luafilesystem                                  jamessan                                 git@github.com:jamessan/luafilesystem.git                                        $# $@
register_remote src/thirdparty/luafilesystem                                  jaromil                                  git@github.com:jaromil/luafilesystem.git                                         $# $@
register_remote src/thirdparty/luafilesystem                                  javalikescript                           git@github.com:javalikescript/luafilesystem.git                                  $# $@
register_remote src/thirdparty/luafilesystem                                  jeduden                                  git@github.com:jeduden/luafilesystem.git                                         $# $@
register_remote src/thirdparty/luafilesystem                                  keplerproject                            git@github.com:keplerproject/luafilesystem.git                                   $# $@
register_remote src/thirdparty/luafilesystem                                  keplerproject-original                   git@github.com:keplerproject/luafilesystem.git                                   $# $@
register_remote src/thirdparty/luafilesystem                                  ldmiao                                   git@github.com:ldmiao/luafilesystem.git                                          $# $@
register_remote src/thirdparty/luafilesystem                                  lesslol                                  git@github.com:lesslol/luafilesystem.git                                         $# $@
register_remote src/thirdparty/luafilesystem                                  lidesdk                                  git@github.com:lidesdk/lfs.git                                                   $# $@
register_remote src/thirdparty/luafilesystem                                  lorry-lee                                git@github.com:lorry-lee/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  madmaxoft                                git@github.com:madmaxoft/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  mark-perfect                             git@github.com:mark-perfect/luafilesystem.git                                    $# $@
register_remote src/thirdparty/luafilesystem                                  mcclure                                  git@github.com:mcclure/luafilesystem.git                                         $# $@
register_remote src/thirdparty/luafilesystem                                  mjopenglsdl                              git@github.com:mjopenglsdl/luafilesystem.git                                     $# $@
register_remote src/thirdparty/luafilesystem                                  mpeterv                                  git@github.com:mpeterv/luafilesystem.git                                         $# $@
register_remote src/thirdparty/luafilesystem                                  n1tehawk                                 git@github.com:n1tehawk/luafilesystem.git                                        $# $@
register_remote src/thirdparty/luafilesystem                                  nixerr                                   git@github.com:nixerr/luafilesystem.git                                          $# $@
register_remote src/thirdparty/luafilesystem                                  pssc                                     git@github.com:pssc/luafilesystem.git                                            $# $@
register_remote src/thirdparty/luafilesystem                                  sonoro1234                               git@github.com:sonoro1234/luafilesystem-1.git                                    $# $@
register_remote src/thirdparty/luafilesystem                                  swerg                                    git@github.com:swerg/qlua-luafilesystem.git                                      $# $@
register_remote src/thirdparty/luafilesystem                                  technomancy                              git@github.com:technomancy/luafilesystem.git                                     $# $@
register_remote src/thirdparty/luafilesystem                                  trms                                     git@github.com:trms/luafilesystem.git                                            $# $@
register_remote src/thirdparty/luafilesystem                                  tst2005                                  git@github.com:tst2005/luafilesystem.git                                         $# $@
register_remote src/thirdparty/luafilesystem                                  utmhikari                                git@github.com:utmhikari/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  uudiin                                   git@github.com:uudiin/luafilesystem.git                                          $# $@
register_remote src/thirdparty/luafilesystem                                  ygf420131591                             git@github.com:ygf420131591/luafilesystem.git                                    $# $@
register_remote src/thirdparty/luafilesystem                                  yufei6808                                git@github.com:yufei6808/luafilesystem.git                                       $# $@
register_remote src/thirdparty/luafilesystem                                  zeitgeist87                              git@github.com:zeitgeist87/luafilesystem.git                                     $# $@
register_remote src/thirdparty/popt                                           arsenm                                   git@github.com:arsenm/POPT.git                                                   $# $@
register_remote src/thirdparty/popt                                           devzero2000                              git@github.com:devzero2000/POPT.git                                              $# $@
register_remote src/thirdparty/popt                                           devzero2000-original                     git@github.com:devzero2000/POPT.git                                              $# $@
register_remote src/thirdparty/popt                                           fredericgermain                          git@github.com:fredericgermain/POPT.git                                          $# $@
register_remote src/thirdparty/pthread-win32                                  BlazesRus                                git@github.com:BlazesRus/pthread-win32.git                                       $# $@
register_remote src/thirdparty/pthread-win32                                  Cinegy                                   git@github.com:Cinegy/pthread-win32.git                                          $# $@
register_remote src/thirdparty/pthread-win32                                  DeckerSU                                 git@github.com:DeckerSU/pthread-win32.git                                        $# $@
register_remote src/thirdparty/pthread-win32                                  GerHobbelt                               git@github.com:GerHobbelt/pthread-win32.git                                      $# $@
register_remote src/thirdparty/pthread-win32                                  GerHobbelt-original                      git@github.com:GerHobbelt/pthread-win32.git                                      $# $@
register_remote src/thirdparty/pthread-win32                                  Puasonych                                git@github.com:Puasonych/pthread-win32.git                                       $# $@
register_remote src/thirdparty/pthread-win32                                  UltraCombos                              git@github.com:UltraCombos/pthread-win32.git                                     $# $@
register_remote src/thirdparty/pthread-win32                                  carlo_bramini-pthreads4w                 https://git.code.sf.net/u/userid-1386839/pthreads4w                              $# $@
register_remote src/thirdparty/pthread-win32                                  gandalfliang                             git@github.com:gandalfliang/pthread-win32.git                                    $# $@
register_remote src/thirdparty/pthread-win32                                  h2obrain                                 git@github.com:h2obrain/pthread-win32.git                                        $# $@
register_remote src/thirdparty/pthread-win32                                  hayguen                                  git@github.com:hayguen/pthread-win32.git                                         $# $@
register_remote src/thirdparty/pthread-win32                                  jwinarske-pthreads4w                     https://git.code.sf.net/u/jwinarske/pthreads4w                                   $# $@
register_remote src/thirdparty/pthread-win32                                  mancoast                                 git@github.com:mancoast/pthreads.git                                             $# $@
register_remote src/thirdparty/pthread-win32                                  markpizz-pthreads4w                      https://git.code.sf.net/u/markpizz/pthreads4w                                    $# $@
register_remote src/thirdparty/pthread-win32                                  markpizz-pthreads4w-code                 https://git.code.sf.net/u/markpizz/pthreads4w-code                               $# $@
register_remote src/thirdparty/pthread-win32                                  maxlovic-pthreads4w                      https://git.code.sf.net/u/maxlovic/pthreads4w                                    $# $@
register_remote src/thirdparty/pthread-win32                                  mingw-pthreads4w                         https://git.code.sf.net/p/mingw/pthreads4w                                       $# $@
register_remote src/thirdparty/pthread-win32                                  nicolaichuk                              git@github.com:nicolaichuk/pthread-win32.git                                     $# $@
register_remote src/thirdparty/pthread-win32                                  nikelman2000-pthreads4w                  https://git.code.sf.net/u/nikelman2000/pthreads4w                                $# $@
register_remote src/thirdparty/pthread-win32                                  oktonion                                 git@github.com:oktonion/pthread-win32.git                                        $# $@
register_remote src/thirdparty/pthread-win32                                  pierreguillot                            git@github.com:pierreguillot/pthread-win32.git                                   $# $@
register_remote src/thirdparty/pthread-win32                                  pthreeads4w-sourceforge                  https://git.code.sf.net/p/pthreads4w/code                                        $# $@
register_remote src/thirdparty/pthread-win32                                  raspopov-pthreads4w                      https://git.code.sf.net/u/raspopov/pthreads4w                                    $# $@
register_remote src/thirdparty/pthread-win32                                  rs0h                                     git@github.com:rs0h/pthread-win32.git                                            $# $@
register_remote src/thirdparty/pthread-win32                                  sproberts92                              git@github.com:sproberts92/pthread-win32.git                                     $# $@
register_remote src/thirdparty/selectable-socketpair                          GerHobbelt                               git@github.com:GerHobbelt/selectable-socketpair.git                              $# $@
register_remote src/thirdparty/selectable-socketpair                          mstorsjo                                 git@github.com:mstorsjo/selectable-socketpair.git                                $# $@
register_remote src/thirdparty/selectable-socketpair                          ncm                                      git@github.com:ncm/selectable-socketpair.git                                     $# $@
register_remote src/thirdparty/selectable-socketpair                          ncm-original                             git@github.com:ncm/selectable-socketpair.git                                     $# $@
register_remote src/thirdparty/upskirt                                        13steinj                                 git@github.com:13steinj/snudown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        7890                                     git@github.com:7890/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        CBDB1LOVE                                git@github.com:CBDB1LOVE/sundown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        DGHeroin                                 git@github.com:DGHeroin/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        Daij-Djan                                git@github.com:Daij-Djan/sundown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        Dynactionize                             git@github.com:Dynactionize/hoedown.git                                          $# $@
register_remote src/thirdparty/upskirt                                        GerHobbelt                               git@github.com:GerHobbelt/upskirt.git                                            $# $@
register_remote src/thirdparty/upskirt                                        GerHobbelt-original                      git@github.com:GerHobbelt/upskirt.git                                            $# $@
register_remote src/thirdparty/upskirt                                        JBondi                                   git@github.com:JBondi/snudown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        LibrePCB                                 git@github.com:LibrePCB/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        PeterXu                                  git@github.com:PeterXu/hoedown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        RockfordWei                              git@github.com:RockfordWei/upskirt.git                                           $# $@
register_remote src/thirdparty/upskirt                                        SanderMertens                            git@github.com:SanderMertens/hoedown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        UbunHub                                  git@github.com:UbunHub/hoedown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        Wack0                                    git@github.com:Wack0/snudown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        Yserbius                                 git@github.com:Yserbius/snudown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        Zariel                                   git@github.com:Zariel/snudown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        adeindie                                 git@github.com:adeindie/md_old.git                                               $# $@
register_remote src/thirdparty/upskirt                                        ahmedcharles                             git@github.com:ahmedcharles/hoedown.git                                          $# $@
register_remote src/thirdparty/upskirt                                        ahssas                                   git@github.com:ahssas/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        akinozgen                                git@github.com:akinozgen/scidown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        aleray                                   git@github.com:aleray/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        alex-shpilkin                            git@github.com:alex-shpilkin/sundown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        almassapargali                           git@github.com:almassapargali/sundown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        analog-cbarber                           git@github.com:analog-cbarber/hoedown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        andre-d                                  git@github.com:andre-d/snudown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        andrew-d                                 git@github.com:andrew-d/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        andygeers                                git@github.com:andygeers/sundown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        apiaryio                                 git@github.com:apiaryio/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        apnadkarni                               git@github.com:apnadkarni/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        aroben                                   git@github.com:aroben/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        bdolman                                  git@github.com:bdolman/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        beingryu                                 git@github.com:beingryu/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        bigjason                                 git@github.com:bigjason/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        bmcculley                                git@github.com:bmcculley/hoedown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        bnoordhuis                               git@github.com:bnoordhuis/upskirt.git                                            $# $@
register_remote src/thirdparty/upskirt                                        bootstraponline-archive                  git@github.com:bootstraponline-archive/sundown.git                               $# $@
register_remote src/thirdparty/upskirt                                        brandonc                                 git@github.com:brandonc/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        brson                                    git@github.com:brson/snudown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        cfcommando                               git@github.com:cfcommando/snudown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        chid                                     git@github.com:chid/snudown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        chr-1x                                   git@github.com:chr-1x/sd_markdown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        ckolumbus                                git@github.com:ckolumbus/sundown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        clemensg                                 git@github.com:clemensg/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        cloose                                   git@github.com:cloose/hoedown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        danffer2019                              git@github.com:danffer2019/hoedown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        danry25                                  git@github.com:danry25/snudown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        dasslefl                                 git@github.com:dasslefl/scidown-wasm.git                                         $# $@
register_remote src/thirdparty/upskirt                                        datacratic                               git@github.com:datacratic/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        davidask                                 git@github.com:davidask/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        davidpshea                               git@github.com:davidpshea/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        debuggio                                 git@github.com:debuggio/snudown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        demon36                                  git@github.com:demon36/hoedown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        dispatchqueue                            git@github.com:dispatchqueue/sundown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        doo                                      git@github.com:doo/hoedown.git                                                   $# $@
register_remote src/thirdparty/upskirt                                        durka                                    git@github.com:durka/snudown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        dustlang                                 git@github.com:dustlang/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        eichlan                                  git@github.com:eichlan/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        empyrical                                git@github.com:empyrical/snudown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        erikdesjardins                           git@github.com:erikdesjardins/snudown-js.git                                     $# $@
register_remote src/thirdparty/upskirt                                        errpro                                   git@github.com:errpro/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        fabb                                     git@github.com:fabb/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        fappelman                                git@github.com:fappelman/hoedown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        faywong                                  git@github.com:faywong/scidown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        fergaschas                               git@github.com:fergaschas/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        fluffy-critter                           git@github.com:fluffy-critter/hoedown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        freron                                   git@github.com:freron/upskirt.git                                                $# $@
register_remote src/thirdparty/upskirt                                        gagern                                   git@github.com:gagern/hoedown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        gampleman                                git@github.com:gampleman/Sunrise.git                                             $# $@
register_remote src/thirdparty/upskirt                                        geoffmcl                                 git@github.com:geoffmcl/scidown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        gregleaver                               git@github.com:gregleaver/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        gwynne                                   git@github.com:gwynne/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        hispeedimagins                           git@github.com:hispeedimagins/hoedown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        hoedown                                  git@github.com:hoedown/hoedown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        ignatenkobrain                           git@github.com:ignatenkobrain/hoedown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        immunant                                 git@github.com:immunant/snudown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        jacksonh                                 git@github.com:jacksonh/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        jasharpe                                 git@github.com:jasharpe/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        jayvn                                    git@github.com:jayvn/hoedown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        jercos                                   git@github.com:jercos/snudown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        jgoz                                     git@github.com:jgoz/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        jimmyjxiao                               git@github.com:jimmyjxiao/hoedown-cpp.git                                        $# $@
register_remote src/thirdparty/upskirt                                        jjude                                    git@github.com:jjude/sundown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        jmendeth                                 git@github.com:jmendeth/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        jmtd                                     git@github.com:jmtd/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        jnicklas                                 git@github.com:jnicklas/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        jsayol                                   git@github.com:jsayol/snudown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        jsoref                                   git@github.com:jsoref/hoedown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        kidaak                                   git@github.com:kidaak/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        krig                                     git@github.com:krig/hoedown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        kripken                                  git@github.com:kripken/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        lepture                                  git@github.com:lepture/hoedown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        locallycompact                           git@github.com:locallycompact/hoedown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        marc-sturm                               git@github.com:marc-sturm/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        marcheiligers                            git@github.com:marcheiligers/sundown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        marcomaggi                               git@github.com:marcomaggi/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        matthewryan                              git@github.com:matthewryan/sundown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        meldonization                            git@github.com:meldonization/hoedown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        michaelrsweet                            git@github.com:michaelrsweet/rfcdown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        miguelsaldivar                           git@github.com:miguelsaldivar/snudown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        mikecsh                                  git@github.com:mikecsh/hoedown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        mildsunrise                              git@github.com:mildsunrise/hoedown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        milgner                                  git@github.com:milgner/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        mingodad                                 git@github.com:mingodad/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        moejoe                                   git@github.com:moejoe/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        mohd-akram                               git@github.com:mohd-akram/snudown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        nandhp                                   git@github.com:nandhp/snudown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        new-day-international                    git@github.com:new-day-international/snudown.git                                 $# $@
register_remote src/thirdparty/upskirt                                        njdehoog                                 git@github.com:njdehoog/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        njlr                                     git@github.com:njlr/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        nkhorman                                 git@github.com:nkhorman/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        nono                                     git@github.com:nono/upskirt.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        nullice                                  git@github.com:nullice/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        parallaxinc                              git@github.com:parallaxinc/hoedown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        paulcbetts                               git@github.com:paulcbetts/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        pazos                                    git@github.com:pazos/hoedown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        pfgithub                                 git@github.com:pfgithub/snudown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        q--                                      git@github.com:q--/snudown.git                                                   $# $@
register_remote src/thirdparty/upskirt                                        randomatom                               git@github.com:randomatom/hoedown-mweb.git                                       $# $@
register_remote src/thirdparty/upskirt                                        reddit                                   git@github.com:reddit/snudown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        robert-h-at-cp                           git@github.com:robert-h-at-cp/snudown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        robin                                    git@github.com:robin/sundown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        rram                                     git@github.com:rram/snudown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        rschiang                                 git@github.com:rschiang/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        rstudio                                  git@github.com:rstudio/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        rust-lang                                git@github.com:rust-lang/hoedown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        rwos                                     git@github.com:rwos/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        safx                                     git@github.com:safx/hoedown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        samdroid-apps                            git@github.com:samdroid-apps/snudown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        sim0629                                  git@github.com:sim0629/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        sschober                                 git@github.com:sschober/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        steve-wolter                             git@github.com:steve-wolter/hoedown.git                                          $# $@
register_remote src/thirdparty/upskirt                                        strivingboy                              git@github.com:strivingboy/hoedown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        tamlok                                   git@github.com:tamlok/hoedown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        tomaz                                    git@github.com:tomaz/sundown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        txdv                                     git@github.com:txdv/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        uranusjr                                 git@github.com:uranusjr/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        vmg                                      git@github.com:vmg/sundown.git                                                   $# $@
register_remote src/thirdparty/upskirt                                        vmg-original                             git@github.com:vmg/sundown.git                                                   $# $@
register_remote src/thirdparty/upskirt                                        waldyrious                               git@github.com:waldyrious/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        xrfind                                   git@github.com:xrfind/hoedown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        xxbastekxx                               git@github.com:xxbastekxx/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        yoannsculo                               git@github.com:yoannsculo/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        zababurinsv                              git@github.com:zababurinsv/sundown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        zeantsoi                                 git@github.com:zeantsoi/snudown.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter                            GerHobbelt                               git@github.com:GerHobbelt/charter.git                                            $# $@
register_remote src/thirdparty/upskirt/src/charter                            Mandarancio                              git@github.com:Mandarancio/charter.git                                           $# $@
register_remote src/thirdparty/upskirt/src/charter                            Mandarancio-original                     git@github.com:Mandarancio/charter.git                                           $# $@
register_remote src/thirdparty/upskirt/src/charter                            dasslefl                                 git@github.com:dasslefl/charter-wasm.git                                         $# $@
register_remote src/thirdparty/upskirt/src/charter                            faywong                                  git@github.com:faywong/charter.git                                               $# $@
register_remote src/thirdparty/upskirt/src/charter                            geoffmcl                                 git@github.com:geoffmcl/charter.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               AntonC9018                               git@github.com:AntonC9018/tinyexpr.git                                           $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               Blake-Madden                             git@github.com:Blake-Madden/tinyexpr-plusplus.git                                $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               BobBurns                                 git@github.com:BobBurns/tinyexpr.git                                             $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               Eric-zambom                              git@github.com:Eric-zambom/tinyexpr.git                                          $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               GUUSTA                                   git@github.com:GUUSTA/tinyexpr.git                                               $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               MaxFork                                  git@github.com:MaxFork/tinyexpr.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               MeshFEM                                  git@github.com:MeshFEM/tinyexpr.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               RaiKoHoff                                git@github.com:RaiKoHoff/tinyexpr.git                                            $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               aseprite                                 git@github.com:aseprite/tinyexpr.git                                             $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               chendotjs                                git@github.com:chendotjs/tinyexpr.git                                            $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               codeplea                                 git@github.com:codeplea/tinyexpr.git                                             $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               cri-s                                    git@github.com:cri-s/tinyexpr.git                                                $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               cschreib                                 git@github.com:cschreib/tinyexpr.git                                             $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               davesvnbrger                             git@github.com:davesvnbrger/tinyexpr.git                                         $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               dendisuhubdy                             git@github.com:dendisuhubdy/tinyexpr.git                                         $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               dilawar                                  git@github.com:dilawar/tinyexpr.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               domsoll                                  git@github.com:domsoll/tinyexpr.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               geoffmcl                                 git@github.com:geoffmcl/tinyexpr.git                                             $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               giacomo-b                                git@github.com:giacomo-b/tinyexpr.git                                            $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               hbqzq                                    git@github.com:hbqzq/tinyexpr.git                                                $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               luizrgguimaraes                          git@github.com:luizrgguimaraes/tinyexpr.git                                      $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               mortie                                   git@github.com:mortie/tinyexpr.git                                               $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               niltonvasques                            git@github.com:niltonvasques/tinyexpr.git                                        $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               polyfem                                  git@github.com:polyfem/tinyexpr.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               ricxsar                                  git@github.com:ricxsar/tinyexpr.git                                              $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               sdmg15                                   git@github.com:sdmg15/tinyexpr.git                                               $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               spartrekus                               git@github.com:spartrekus/Tinyexprfork.git                                       $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               stawiski                                 git@github.com:stawiski/tinyexpr.git                                             $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               tylov-fork                               git@github.com:tylov-fork/tinyexpr.git                                           $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               victorliu                                git@github.com:victorliu/tinyexpr.git                                            $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               weliveindetail                           git@github.com:weliveindetail/tinyexpr.git                                       $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               xiehuc                                   git@github.com:xiehuc/tinyexpr.git                                               $# $@
register_remote src/thirdparty/upskirt/src/charter/src/tinyexpr               y11en                                    git@github.com:y11en/tinyexpr.git                                                $# $@



popd                                                                            2> /dev/null   > /dev/null

