#! /bin/bash
# generated by collect_git_remote_add_recursively.sh

pushd $(dirname $0)                                                             2> /dev/null   > /dev/null
cd ..

mode="d"

getopts ":fqh" opt
#echo opt+arg = "$opt$OPTARG"
case "$opt$OPTARG" in
f )
  echo "--- check out master/HEAD before registering all git remotes ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="f"

  git submodule sync
  git submodule update --init
  git submodule update --init --recursive

  util/git_checkout_submodules_head.sh
  ;;

"?" )
  echo "--- set up git remotes only ---"
  ;;

q )
  echo "--- set up git remotes only ---"
  for (( i=OPTIND; i > 1; i-- )) do
    shift
  done
  #echo args: $@
  mode="q"
  ;;

* )
  cat <<EOT
$0 [-f] [-q] [submodule-paths]

set up git remotes for any / all submodules.

-f       : 'full featured', i.e. check out the preferred branch for each submodule
           and register all submodule remotes.
-q       : 'quick', i.e. only register all submodule remotes.
submodule-paths
         : when you specify one or more submodule directories, than only the
           remotes for those submodules will be set up.
           This is optional; the default sets up the remotes for ALL submodules.

EOT
  exit
  ;;
esac


submodule=xxxxxx

# args: (path, name, repo, argc, argv...)
function register_remote {
    argc=$#
    argv=("$@")
    path=$1
    name=$2
    repo=$3
    #echo register_remote [$path] [$name] [$repo] [$argc] [...]

    # only when paths have been specified on the commandline do we check whether the given remote should be registered
    # (apart from the separate check to see if the submodule has actually been installed, see further below)
    if test $argc -gt 4 ; then
        hit=0
        for ((i=4; i < $argc; i++)); do
            #echo testing dir $i: ${argv[$i]}
            if test ${argv[$i]} = $path ; then
                hit=1
                break
            fi
        done
    else
        hit=1
    fi

    if test $hit -ne 0 ; then
        if test -d $path && test -s $path/.git ; then
            if test $submodule != $path ; then
                echo -------------------------------------------------------------------------------------
                echo submodule:: $path
                submodule=$path
            fi
            pushd $path                                                         2> /dev/null   > /dev/null
            if test "$mode" = "f" ; then
                git remote rm $name
            fi
            git remote add $name $repo
            popd                                                                2> /dev/null   > /dev/null
        fi
    fi
}






register_remote .                                                             BaroboRobotics                           git@github.com:BaroboRobotics/civetweb.git                                       $# $@
register_remote .                                                             CognitiveNetworks                        git@github.com:CognitiveNetworks/civetweb.git                                    $# $@
register_remote .                                                             Enseed                                   git@github.com:Enseed/civetweb.git                                               $# $@
register_remote .                                                             GerHobbelt-original                      git@github.com:GerHobbelt/civet-webserver.git                                    $# $@
register_remote .                                                             Grahack                                  git@github.com:Grahack/civetweb.git                                              $# $@
register_remote .                                                             NetDevLtd                                git@github.com:NetDevLtd/civetweb.git                                            $# $@
register_remote .                                                             Rjinswand                                git@github.com:Rjinswand/civetweb.git                                            $# $@
register_remote .                                                             SafwatHalaby                             git@github.com:SafwatHalaby/civetweb.git                                         $# $@
register_remote .                                                             alemv                                    git@github.com:alemv/civetweb.git                                                $# $@
register_remote .                                                             apetrone                                 git@github.com:apetrone/civetweb.git                                             $# $@
register_remote .                                                             c2go                                     git@github.com:c2go/civetweb.git                                                 $# $@
register_remote .                                                             cdbishop                                 git@github.com:cdbishop/civetweb.git                                             $# $@
register_remote .                                                             ceph                                     git@github.com:ceph/civetweb.git                                                 $# $@
register_remote .                                                             civetweb                                 git@github.com:civetweb/civetweb.git                                             $# $@
register_remote .                                                             dalgaaf                                  git@github.com:dalgaaf/civetweb.git                                              $# $@
register_remote .                                                             detro                                    git@github.com:detro/civetweb.git                                                $# $@
register_remote .                                                             fgaranda                                 git@github.com:fgaranda/civetweb.git                                             $# $@
register_remote .                                                             jdblair                                  git@github.com:jdblair/civetweb.git                                              $# $@
register_remote .                                                             jesperes                                 git@github.com:jesperes/civetweb.git                                             $# $@
register_remote .                                                             leonardosantos                           git@github.com:leonardosantos/civetta.git                                        $# $@
register_remote .                                                             local-server                             ../../../../../hundman-photography.gov/80/__server/htdocs/lib/civet-webserver/   $# $@
register_remote .                                                             rpetrich                                 git@github.com:rpetrich/civetweb.git                                             $# $@
register_remote .                                                             rzarzynski                               git@github.com:rzarzynski/civetweb.git                                           $# $@
register_remote .                                                             samcrow                                  git@github.com:samcrow/civetweb.git                                              $# $@
register_remote .                                                             shawnye                                  git@github.com:shawnye/civetweb.git                                              $# $@
register_remote .                                                             tnoho                                    git@github.com:tnoho/civetweb.git                                                $# $@
register_remote .                                                             tracedev                                 git@github.com:tracedev/civetweb.git                                             $# $@
register_remote .                                                             uhertlein                                git@github.com:uhertlein/civetweb.git                                            $# $@
register_remote .                                                             vcatechnology                            git@github.com:vcatechnology/civetweb.git                                        $# $@
register_remote .                                                             xtne6f                                   git@github.com:xtne6f/civetweb.git                                               $# $@
register_remote src/thirdparty/popt                                           arsenm                                   git@github.com:arsenm/POPT.git                                                   $# $@
register_remote src/thirdparty/popt                                           devzero2000                              git@github.com:devzero2000/POPT.git                                              $# $@
register_remote src/thirdparty/popt                                           devzero2000-original                     git@github.com:devzero2000/POPT.git                                              $# $@
register_remote src/thirdparty/popt                                           fredericgermain                          git@github.com:fredericgermain/POPT.git                                          $# $@
register_remote src/thirdparty/pthread-win32                                  GerHobbelt                               git@github.com:GerHobbelt/pthread-win32.git                                      $# $@
register_remote src/thirdparty/pthread-win32                                  GerHobbelt-original                      git@github.com:GerHobbelt/pthread-win32.git                                      $# $@
register_remote src/thirdparty/pthread-win32                                  mancoast                                 git@github.com:mancoast/pthreads.git                                             $# $@
register_remote src/thirdparty/pthread-win32                                  nicolaichuk                              git@github.com:nicolaichuk/pthread-win32.git                                     $# $@
register_remote src/thirdparty/pthread-win32                                  sproberts92                              git@github.com:sproberts92/pthread-win32.git                                     $# $@
register_remote src/thirdparty/selectable-socketpair                          GerHobbelt                               git@github.com:GerHobbelt/selectable-socketpair.git                              $# $@
register_remote src/thirdparty/selectable-socketpair                          mstorsjo                                 git@github.com:mstorsjo/selectable-socketpair.git                                $# $@
register_remote src/thirdparty/selectable-socketpair                          ncm                                      git@github.com:ncm/selectable-socketpair.git                                     $# $@
register_remote src/thirdparty/selectable-socketpair                          ncm-original                             git@github.com:ncm/selectable-socketpair.git                                     $# $@
register_remote src/thirdparty/upskirt                                        Daij-Djan                                git@github.com:Daij-Djan/sundown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        Dynactionize                             git@github.com:Dynactionize/hoedown.git                                          $# $@
register_remote src/thirdparty/upskirt                                        GerHobbelt                               git@github.com:GerHobbelt/upskirt.git                                            $# $@
register_remote src/thirdparty/upskirt                                        adeindie                                 git@github.com:adeindie/md_old.git                                               $# $@
register_remote src/thirdparty/upskirt                                        ahmedcharles                             git@github.com:ahmedcharles/hoedown.git                                          $# $@
register_remote src/thirdparty/upskirt                                        ahssas                                   git@github.com:ahssas/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        aleray                                   git@github.com:aleray/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        alex-shpilkin                            git@github.com:alex-shpilkin/sundown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        almassapargali                           git@github.com:almassapargali/sundown.git                                        $# $@
register_remote src/thirdparty/upskirt                                        andrew-d                                 git@github.com:andrew-d/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        apiaryio                                 git@github.com:apiaryio/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        apnadkarni                               git@github.com:apnadkarni/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        aroben                                   git@github.com:aroben/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        bdolman                                  git@github.com:bdolman/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        beingryu                                 git@github.com:beingryu/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        bigjason                                 git@github.com:bigjason/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        bnoordhuis                               git@github.com:bnoordhuis/upskirt.git                                            $# $@
register_remote src/thirdparty/upskirt                                        bootstraponline-archive                  git@github.com:bootstraponline-archive/sundown.git                               $# $@
register_remote src/thirdparty/upskirt                                        brandonc                                 git@github.com:brandonc/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        ckolumbus                                git@github.com:ckolumbus/sundown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        clemensg                                 git@github.com:clemensg/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        cloose                                   git@github.com:cloose/hoedown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        datacratic                               git@github.com:datacratic/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        doo                                      git@github.com:doo/hoedown.git                                                   $# $@
register_remote src/thirdparty/upskirt                                        eichlan                                  git@github.com:eichlan/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        errpro                                   git@github.com:errpro/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        fergaschas                               git@github.com:fergaschas/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        freron                                   git@github.com:freron/upskirt.git                                                $# $@
register_remote src/thirdparty/upskirt                                        gampleman                                git@github.com:gampleman/Sunrise.git                                             $# $@
register_remote src/thirdparty/upskirt                                        gregleaver                               git@github.com:gregleaver/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        gwynne                                   git@github.com:gwynne/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        hoedown                                  git@github.com:hoedown/hoedown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        jacksonh                                 git@github.com:jacksonh/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        jgoz                                     git@github.com:jgoz/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        jjude                                    git@github.com:jjude/sundown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        jmendeth                                 git@github.com:jmendeth/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        jnicklas                                 git@github.com:jnicklas/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        kripken                                  git@github.com:kripken/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        marc-sturm                               git@github.com:marc-sturm/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        marcheiligers                            git@github.com:marcheiligers/sundown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        marcomaggi                               git@github.com:marcomaggi/hoedown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        matthewryan                              git@github.com:matthewryan/sundown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        michaelrsweet                            git@github.com:michaelrsweet/rfcdown.git                                         $# $@
register_remote src/thirdparty/upskirt                                        milgner                                  git@github.com:milgner/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        moejoe                                   git@github.com:moejoe/sundown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        njdehoog                                 git@github.com:njdehoog/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        nono                                     git@github.com:nono/upskirt.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        nullice                                  git@github.com:nullice/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        paulcbetts                               git@github.com:paulcbetts/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        robin                                    git@github.com:robin/sundown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        rstudio                                  git@github.com:rstudio/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        rust-lang                                git@github.com:rust-lang/hoedown.git                                             $# $@
register_remote src/thirdparty/upskirt                                        rwos                                     git@github.com:rwos/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        safx                                     git@github.com:safx/hoedown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        sim0629                                  git@github.com:sim0629/sundown.git                                               $# $@
register_remote src/thirdparty/upskirt                                        sschober                                 git@github.com:sschober/sundown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        steve-wolter                             git@github.com:steve-wolter/hoedown.git                                          $# $@
register_remote src/thirdparty/upskirt                                        strivingboy                              git@github.com:strivingboy/hoedown.git                                           $# $@
register_remote src/thirdparty/upskirt                                        tomaz                                    git@github.com:tomaz/sundown.git                                                 $# $@
register_remote src/thirdparty/upskirt                                        txdv                                     git@github.com:txdv/sundown.git                                                  $# $@
register_remote src/thirdparty/upskirt                                        uranusjr                                 git@github.com:uranusjr/hoedown.git                                              $# $@
register_remote src/thirdparty/upskirt                                        vmg                                      git@github.com:vmg/sundown.git                                                   $# $@
register_remote src/thirdparty/upskirt                                        vmg-original                             git@github.com:vmg/sundown.git                                                   $# $@
register_remote src/thirdparty/upskirt                                        xrfind                                   git@github.com:xrfind/hoedown.git                                                $# $@
register_remote src/thirdparty/upskirt                                        xxbastekxx                               git@github.com:xxbastekxx/sundown.git                                            $# $@
register_remote src/thirdparty/upskirt                                        yoannsculo                               git@github.com:yoannsculo/sundown.git                                            $# $@



popd                                                                            2> /dev/null   > /dev/null

